version: "3.8"

services:
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    ports:
      - "8010:8010"
    restart: unless-stopped

  web:
    build: .
    container_name: grammarlens
    ports:
      - "80:5000"
    depends_on:
      - languagetool
    restart: unless-stopped
